### ISSUE TITLE
[EPIC] Handle all Incoming SSE Events

### ISSUE THREAD

**Issue by abdulrabbani00** [cerc-io/ipld-eth-beacon-indexer#19]
- [Overview](#overview)
  - [Description](#description)
- [Dependencies](#dependencies)
- [Context](#context)
- [Issues](#issues)
- [Acceptance criteria](#acceptance-criteria)
  - [Proof](#proof)

<small><i><a href='http://ecotrust-canada.github.io/markdown-toc/'>Table of contents generated with markdown-toc</a></i></small>

# Overview

- **Owner**: @abdulrabbani00 
- **Stakeholder Point of Contact**: @abdulrabbani00 

## Description

This epic will capture all the tasks needed to capture and processes blocks from various SSE events. Once the features have been added we need to ensure that the tests have also been added. Currently, we can get the SSE events and turn them into structs. But now we must handle those events properly.

# Dependencies

* We need to be able to interact with the beacon chain: https://github.com/vulcanize/ipld-ethcl-indexer/issues/17

# Context

This issue is focused primarily on handling the SSE events. This scenario is only enacted when tracking the head of the chain.

# Issues

- [x] https://github.com/vulcanize/ipld-ethcl-indexer/issues/21
- [x] https://github.com/vulcanize/ipld-ethcl-indexer/issues/20
- [x] https://github.com/vulcanize/ipld-ethcl-indexer/issues/22
- [x] https://github.com/vulcanize/ipld-ethcl-indexer/issues/23
- [x] https://github.com/vulcanize/ipld-ethcl-indexer/issues/29
- [x] https://github.com/vulcanize/ipld-ethcl-indexer/issues/31
- [x] https://github.com/vulcanize/ipld-ethcl-indexer/issues/32

# Acceptance criteria

* Properly handle events from the `head`, `reorg_chain`, and `finalized_endpoint` topics.
* Handle the happy path, conflicts, missing data, errors, etc.
* Include testing.
