### ISSUE TITLE
[EPIC] Incorporate Historical Processing to the Application

### ISSUE THREAD

**Issue by abdulrabbani00** [cerc-io/ipld-eth-beacon-indexer#42]
- [Overview](#overview)
  - [Description](#description)
- [Dependencies](#dependencies)
- [Context](#context)
- [Issues](#issues)
- [Acceptance criteria](#acceptance-criteria)
  - [Proof](#proof)

<small><i><a href='http://ecotrust-canada.github.io/markdown-toc/'>Table of contents generated with markdown-toc</a></i></small>

# Overview

- **Owner**: @abdulrabbani00 
- **Stakeholder Point of Contact**: @abdulrabbani00 

## Description

At this point in time (`v0.1.0`) the application is capable of performing head tracking. We now need to make sure the application can process historical slots. Either from the `historical_processing` table or from the `known_gaps` table (or any other arbitrary table with a start and end block).

# Dependencies

No known dependencies.

# Context

We need this feature to capture the entire beacon chain.

# Issues

- [x] https://github.com/vulcanize/ipld-ethcl-indexer/issues/43
- [x] https://github.com/vulcanize/ipld-ethcl-indexer/issues/44
- [x] https://github.com/vulcanize/ipld-ethcl-indexer/issues/47
- [x]  https://github.com/vulcanize/ipld-ethcl-indexer/issues/48
- [x] https://github.com/vulcanize/ipld-ethcl-indexer/issues/54
- [x] https://github.com/vulcanize/ipld-ethcl-indexer/issues/52
- [x] https://github.com/vulcanize/ipld-ethcl-indexer/issues/50

# Acceptance criteria

* Passing Tests.
* The ability to capture historical blocks from various phases.
* Integration tests on live data.
* Prometheus Metrics.
